import React from 'react';
import { X, Sparkles, CheckCircle2, ShieldCheck, Database, FileText } from 'lucide-react';

export default function AiDiagnosisCard({ item, onClose, onResolve }) {
  if (!item) return null;

  const ai = item.aiInvestigation;
  const isLiveGemini = ai?.source === 'GEMINI';

  const formatCurrency = (val, currency = 'INR') => {
    if (val === null || val === undefined) return '—';
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: currency || 'INR',
      maximumFractionDigits: 2,
    }).format(val);
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        {/* Modal Header */}
        <div className="modal-header">
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Sparkles size={18} color={isLiveGemini ? "#10B981" : "#F59E0B"} />
              <h3 style={{ fontSize: '18px', fontWeight: 800 }}>AI Root-Cause Diagnosis</h3>
            </div>
            <p style={{ fontSize: '13px', color: '#6B7280', marginTop: '2px' }}>
              {isLiveGemini
                ? 'Autonomous investigation generated by Gemini 3.6 Flash'
                : 'Deterministic domain-grounded financial rules analysis'}
            </p>
          </div>
          <button className="modal-close-btn" onClick={onClose}>
            <X size={18} />
          </button>
        </div>

        {/* Transaction Overview Pill */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          background: '#F9FAFB',
          padding: '14px 18px',
          borderRadius: '16px',
          marginBottom: '20px',
          border: '1px solid rgba(0,0,0,0.05)'
        }}>
          <div>
            <span style={{ fontSize: '11px', textTransform: 'uppercase', color: '#6B7280', fontWeight: 700 }}>
              Transaction Reference
            </span>
            <div style={{ fontWeight: 800, fontSize: '16px', marginTop: '2px' }}>
              {item.transactionId || 'Unknown ID'}
            </div>
          </div>
          <div style={{ textAlign: 'right' }}>
            <span style={{ fontSize: '11px', textTransform: 'uppercase', color: '#6B7280', fontWeight: 700 }}>
              Discrepancy Amount
            </span>
            <div style={{ fontWeight: 800, fontSize: '16px', color: '#DC2626', marginTop: '2px' }}>
              {formatCurrency(item.differenceAmount, item.currency)}
            </div>
          </div>
        </div>

        {/* AI Confidence & Source Badge */}
        {ai && (
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '20px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <span className="confidence-chip">
                <ShieldCheck size={14} />
                <span>{Math.round(ai.confidence * 100)}% Confidence</span>
              </span>
              <span style={{
                fontSize: '12px',
                fontWeight: 700,
                padding: '4px 10px',
                borderRadius: '999px',
                background: isLiveGemini ? '#DCFCE7' : '#FEF3C7',
                color: isLiveGemini ? '#15803D' : '#92400E',
                border: isLiveGemini ? '1px solid #BBF7D0' : '1px solid #FDE68A'
              }}>
                {isLiveGemini ? '✨ Gemini AI • Live' : '⚙️ Demo / Fallback Mode'}
              </span>
            </div>
            <span style={{ fontSize: '12px', color: '#6B7280' }}>
              Investigated: {new Date(ai.investigatedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
            </span>
          </div>
        )}

        {/* Reason Section */}
        <div className="modal-body-section">
          <div className="modal-section-title">Root-Cause Analysis</div>
          <div className="modal-text">
            {ai?.possibleReason || item.discrepancyReason || 'Awaiting AI investigation...'}
          </div>
        </div>

        {/* Recommended Action Section */}
        <div className="modal-body-section" style={{ background: '#F0FDF4', borderColor: '#BBF7D0' }}>
          <div className="modal-section-title" style={{ color: '#15803D' }}>
            Prescribed Controller Action
          </div>
          <div className="modal-text" style={{ color: '#14532D', fontWeight: 600 }}>
            {ai?.recommendedAction || 'Execute manual review of payment transaction and bank nodal ledger.'}
          </div>
        </div>

        {/* Evidence Section */}
        <div className="modal-body-section">
          <div className="modal-section-title">Strict Data Evidence</div>
          <div className="modal-text" style={{ fontSize: '13px', color: '#4B5563' }}>
            {ai?.evidence || `Payment Amount: ${formatCurrency(item.paymentAmount)}, Settled: ${formatCurrency(item.settledAmount)}, Status: ${item.status}`}
          </div>
        </div>

        {/* Action Footer */}
        <div style={{ display: 'flex', gap: '12px', marginTop: '24px' }}>
          <button
            onClick={onClose}
            style={{
              flex: 1,
              padding: '12px',
              borderRadius: '999px',
              border: '1px solid #E5E7EB',
              background: '#FFFFFF',
              color: '#374151',
              fontWeight: 700,
              fontSize: '13px',
              cursor: 'pointer'
            }}
          >
            Dismiss
          </button>
          <button
            onClick={() => {
              alert(`Action Recorded: ${ai?.recommendedAction || 'Adjustment applied'}`);
              onClose();
            }}
            style={{
              flex: 1,
              padding: '12px',
              borderRadius: '999px',
              border: 'none',
              background: '#111827',
              color: '#FFFFFF',
              fontWeight: 700,
              fontSize: '13px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '6px'
            }}
          >
            <CheckCircle2 size={16} />
            <span>Apply Resolution</span>
          </button>
        </div>
      </div>
    </div>
  );
}
